In [1]:
from smpl_io import io
import pandas as pd

In [2]:
def rename(test_df):
    test_df = test_df.rename(columns={1: 'in_1', 2: 'in_2',3:'out_1',4:'out_2', 5:'out_3'})
    test_df = test_df.rename(columns={6:  'p_1_0',  7: 'p_1_1', 8:'p_1_2', 9:'p_1_3'})
    test_df = test_df.rename(columns={10: 'p_2_0', 11: 'p_2_1',12:'p_2_2',13:'p_2_3'})
    test_df = test_df.rename(columns={14: 'p_3_0', 15: 'p_3_1',16:'p_3_2',17:'p_3_3'})
    test_df = test_df.rename(columns={18: 'p_4_0', 19: 'p_4_1',20:'p_4_2',21:'p_4_3'})
    test_df = test_df.rename(columns={22: 'p_5_0', 23: 'p_5_1',24:'p_5_2',25:'p_5_3'})
    test_df = test_df.rename(columns={26: 'alpha'})
    test_df = test_df.rename(columns={27: 'alphas'})
    test_df = test_df.rename(columns={28: 'Born'})
    test_df = test_df.rename(columns={29: 'Virt'})
    return test_df

In [3]:
def mask(ol_df):
    return (ol_df[1] == "2" )&(ol_df[2] == "1" )&(ol_df[3] == "22" )&(ol_df[4] == "2" )&(ol_df[5] == "1" )
    return (ol_df[3] == "22" )

In [4]:
ol_df = pd.read_csv(io.between("START COMP DEBUG","STOP COMP DEBUG",
                       "/home/apn/git/powheg-box-v2/directphotonjj/testrun-lhc/bench-openloops/working/run-st1-xg1-1.log"
                      ),
            header=None,
            delimiter='\s+',
           )

ol_df = ol_df[(ol_df[0] != "Thanks") & (ol_df[0] != "Eur.Phys.J.")]
ol_df= ol_df.set_index(0)
ol_df = ol_df [ mask(ol_df)][0:10]
ol_df = rename(ol_df)

In [5]:
mg_df = ol_df.copy()
rc_df = ol_df.copy()

In [6]:
fc_df= pd.read_csv(io.between("START COMP DEBUG","STOP COMP DEBUG",
                       "/home/apn/git/powheg-box-v2/directphotonjj/testrun-lhc/bench-formcalc/working/run-st1-xg1-1.log"),
            header=None,
            delimiter='\s+',
           )
fc_df = fc_df[(fc_df[0] != "Thanks") & (fc_df[0] != "Eur.Phys.J.")]  
fc_df= fc_df.set_index(0)  
fc_df = fc_df [mask(fc_df)][0:10]
fc_df

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,26,27,28,29
0,,,,,,,,,,,,,,,,,,,,,
2361,2,1,22,2,1,1277.063097,0.0,0.0,1277.063097,1277.063097,...,124.522527,-195.042588,1235.467758,-829.878591,-517.110575,755.168033,0.118775,0.007297,1.091636e-06,-0.000053
2362,2,1,22,2,1,1118.152701,0.0,0.0,1118.152701,1118.152701,...,-885.214749,-197.638457,805.559861,-89.324745,794.883506,95.435797,0.118775,0.007297,3.895594e-06,-0.000218
2363,2,1,22,2,1,1504.385578,0.0,0.0,1504.385578,1504.385578,...,241.991581,-575.111406,1239.655387,-847.814715,683.863100,591.850443,0.118775,0.007297,4.651473e-07,-0.000020
2364,2,1,22,2,1,1550.356508,0.0,0.0,1550.356508,1550.356508,...,-516.464717,404.342194,1125.700057,-179.338944,1110.918523,-29.969945,0.118775,0.007297,1.037161e-06,-0.000082
2365,2,1,22,2,1,1152.656664,0.0,0.0,1152.656664,1152.656664,...,-527.951650,-253.301050,715.211822,-686.175033,-121.497597,161.028287,0.118775,0.007297,5.822525e-07,-0.000023
2366,2,1,22,2,1,1710.777511,0.0,0.0,1710.777511,1710.777511,...,794.031660,603.700050,1247.780346,773.123578,-533.059459,-821.634552,0.118775,0.007297,2.347949e-06,-0.000214
2367,2,1,22,2,1,1636.912993,0.0,0.0,1636.912993,1636.912993,...,-872.964404,-308.349084,554.722362,-52.132236,-516.042409,-196.721533,0.118775,0.007297,5.517023e-07,-0.000036
2368,2,1,22,2,1,1425.757452,0.0,0.0,1425.757452,1425.757452,...,-413.679274,-310.497578,835.567414,342.304439,-742.093692,174.061843,0.118775,0.007297,3.295578e-07,-0.000015
2369,2,1,22,2,1,1280.276791,0.0,0.0,1280.276791,1280.276791,...,-371.677912,-840.993821,648.934848,-221.407249,522.898192,314.122186,0.118775,0.007297,1.451404e-06,-0.000056
2370,2,1,22,2,1,1596.425817,0.0,0.0,1596.425817,1596.425817,...,41.350752,-492.693205,1443.564683,1204.142853,701.505684,376.575038,0.118775,0.007297,1.089402e-06,-0.000071

In [7]:
(abs(((ol_df[26]-fc_df[26])/fc_df[26]))).plot(figsize=(20,5),logy=True) # LO

KeyError: 26

In [ ]:
ol_df.index[abs(((ol_df[26]-fc_df[26])/fc_df[26]))>10e-9]

In [ ]:
abs(((ol_df[27]-fc_df[27])/fc_df[27])).plot(figsize=(20,5),logy=True) # Virt